### ISSUE TITLE
Read pineappl grid output path from runcard

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/hawaiian_vrap#19]
At the moment the pineappl grid gets saved as `test.pineappl.lz4` which is not super beautiful. It would be better to either use the name of the runcard or allow for the name to be read from the runcard.

**Comment by cschwan** [comment]
The convention that we follow - I think - is to use the name of the directory in which the runcards are.

**Comment by scarlehoff** [comment]
For the output grid from runcard runner yes, but the grid generated from `vrap` is not the final grid so it would need to have a different name (so actually using the runcard name doesn't work, the only possibility is reading a name from the runcard).
