### ISSUE TITLE
Update dead link to PineAPPL's new homepage

### ISSUE THREAD

**Issue by cschwan** [NNPDF/hawaiian_vrap#24]
In https://github.com/NNPDF/hawaiian_vrap/blob/c370769bfdb56cfec369038998adffa1dad5a92f/src/Vrap.C#L108 we should change the link to <https://nnpdf.github.io/pineappl>.

**Comment by scarlehoff** [comment]
oh, right. Please do!

**Comment by cschwan** [comment]
Fixed in commit 98e16bb38f3a7944ea9de7a247442ccd47f54fad.
